const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));

const sections=[...document.querySelectorAll('main section[id]')];const navLinks=[...nav.querySelectorAll('a')];const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}})},{rootMargin:'-35% 0px -55%'});sections.forEach(s=>observer.observe(s));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const canvas=document.querySelector('#ribbonCanvas');const ctx=canvas.getContext('2d');let w,h,dpr,particles=[];const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){dpr=Math.min(devicePixelRatio,2);w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(90,Math.floor(w/12))},()=>({x:Math.random()*w,y:h*(.25+Math.random()*.55),s:.3+Math.random()*1.5,v:.15+Math.random()*.45,p:Math.random()*6.28}))}resize();addEventListener('resize',resize);
function ribbon(time){ctx.clearRect(0,0,w,h);ctx.globalCompositeOperation='lighter';for(let j=0;j<5;j++){ctx.beginPath();for(let x=0;x<=w;x+=12){const y=h*(.39+j*.075)+Math.sin(x*.006+time*.00045+j*.9)*48+Math.sin(x*.013-time*.00025)*18;ctx[x?'lineTo':'moveTo'](x,y)}const g=ctx.createLinearGradient(0,0,w,0);g.addColorStop(0,'rgba(114,68,8,0)');g.addColorStop(.38,'rgba(180,112,18,.08)');g.addColorStop(.72,'rgba(255,194,70,.2)');g.addColorStop(1,'rgba(255,223,130,0)');ctx.strokeStyle=g;ctx.lineWidth=1+j*.35;ctx.stroke()}particles.forEach(p=>{p.x+=p.v;if(p.x>w)p.x=-5;p.y+=Math.sin(time*.001+p.p)*.08;ctx.fillStyle=`rgba(241,178,54,${.15+p.s*.12})`;ctx.beginPath();ctx.arc(p.x,p.y,p.s,0,Math.PI*2);ctx.fill()});if(!reduce)requestAnimationFrame(ribbon)}if(!reduce)requestAnimationFrame(ribbon);
